// app/layout.tsx
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import ReduxProvider from "./components/ReduxProvider";
import Header from "./components/Header";
import SideNavbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Deed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="./media/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <div className="flex flex-col min-h-screen">
            {/* ✅ Header (always fixed top) */}
            <div className="fixed top-0 left-0 right-0 z-50">
              <Header />
            </div>

            <div className="flex flex-1 pt-16">
              {/* ✅ Sidebar (desktop) */}
              <div className="hidden md:block fixed top-16 left-0 h-[calc(100vh-4rem)] w-60 z-40">
                <SideNavbar />
              </div>

              {/* ✅ Main content */}
              <main
                className="
                  flex-1  pt-6 bg-gray-50 overflow-y-auto
                  md:ml-[160px] md:pb-0
                  pb-16  /* leave space for mobile bottom nav */
                "
              >
                {children}
              </main>
            </div>

            {/* ✅ Bottom nav (mobile only) */}
            <div className="md:hidden fixed bottom-0 left-0 right-0 z-50">
              <SideNavbar />
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
