// store/app/counterSlice.ts
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state of the counter
const initialState = {
  activeTab: "find",
};

// Create a slice
const globalSlice = createSlice({
  name: "global",
  initialState,
  reducers: {
    setActiveTab: (state, action) => {
      state.activeTab = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { setActiveTab } = globalSlice.actions;

// Export the reducer to be added to the store
export default globalSlice.reducer;
